// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntArray.proto

package ru.hse.comparison.protos;

public interface IntArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:comparison.IntArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 size = 1;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>repeated int32 elem = 2;</code>
   * @return A list containing the elem.
   */
  java.util.List<java.lang.Integer> getElemList();
  /**
   * <code>repeated int32 elem = 2;</code>
   * @return The count of elem.
   */
  int getElemCount();
  /**
   * <code>repeated int32 elem = 2;</code>
   * @param index The index of the element to return.
   * @return The elem at the given index.
   */
  int getElem(int index);
}
