// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntArray.proto

package ru.hse.comparison.protos;

public interface IntArrayOrBuilder extends
    // @@protoc_insertion_point(interface_extends:comparison.IntArray)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 size = 1;</code>
   */
  int getSize();

  /**
   * <code>repeated int32 elem = 2;</code>
   */
  java.util.List<java.lang.Integer> getElemList();
  /**
   * <code>repeated int32 elem = 2;</code>
   */
  int getElemCount();
  /**
   * <code>repeated int32 elem = 2;</code>
   */
  int getElem(int index);
}
