// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IntArray.proto

package ru.hse.comparison.protos;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_comparison_IntArray_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_comparison_IntArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016IntArray.proto\022\ncomparison\"&\n\010IntArray" +
      "\022\014\n\004size\030\001 \001(\005\022\014\n\004elem\030\002 \003(\005B%\n\030ru.hse.c" +
      "omparison.protosB\007MessageP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_comparison_IntArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_comparison_IntArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_comparison_IntArray_descriptor,
        new java.lang.String[] { "Size", "Elem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
